<?php
/**
 * @file
 */

/**
 * Implements hook_fb_user().
 *
 * This hook provided by fb_user.module will notify us when a new account is
 * created or a local account is logged in via facebook.
 *
 * @param $op
 *   Indicates what operation is currently being performed, or which behavior
 *   can be customized.  There are a number of these.  In some cases,
 *   modules/fb is informing other modules, and in other operations it is
 *   asking for information.
 *   - FB_USER_OP_PRE_USER - You have a chance to the name or other account
 *     attributes, before a new user account is created.
 *   - FB_USER_OP_POST_USER - A new user account was created for a facebook user
 *     who authorized an app.
 *
 * @param $data
 *   Associative array of information specific to this operation.
 *   Usually, but not always, contains:
 *   - 'fb' - The API provided by the facebook-php-sdk.
 *   - 'fb_app' - The data about this application stored by fb_app.module.
 *   - 'fbu' - If the current user is known, their facebook id.
 *
 * @param $return
 *   An op-specific return value.  Your hook should change this reference
 *   variable, and not return it.  Some operations return an array of data,
 *   which may be collaboratively built by multiple implementations of this
 *   hook.
 *
 */
include_once('ssrx_user.features.inc');

function ssrx_user_fb_user($op, $data, &$return) {
  // dpm($op);
  // dpm($data);
  // dpm($return);
  if ($op == FB_USER_OP_PRE_USER) {
    $fname = $data['info']['first_name'];
    $lname = $data['info']['last_name'];
    $return['field_first_name'][LANGUAGE_NONE][0]['value'] = $fname;
    $return['field_last_name'][LANGUAGE_NONE][0]['value'] = $lname;
  }
}

/**
 * Implements hook_form_alter()
 */
function ssrx_user_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#form_id'] == 'user_register_form') {
    $form['fb_user']['#weight'] = -100;
    // Get rid of na option:
    unset($form['field_gender'][LANGUAGE_NONE]['#options']['_none']);
  }
}

 /**
 * Implementation of hook_menu_alter().
 */
function ssrx_user_menu_alter(&$callbacks) {
  $callbacks['user/register']['title'] = 'Join Us';
  //$callbacks['user/register']['weight'] = -1;
  $callbacks['user/login']['title'] = 'Sign In';
  //$callbacks['user/login']['weight'] = 0;
  //$callbacks['user/password']['weight'] = 1;
}