<?php
/**
 * @file
 * Code for the ssrx_pricereports feature.
 */

include_once 'ssrx_pricereports.features.inc';
/**
 * Implements hook_form_FORM_ID_alter() for the node form.
 */
function ssrx_pricereports_form_node_form_alter(&$form, &$form_state, $form_id) {
  // $form['title']['#value'] = 'ssrx';
  $form['title']['#type'] = 'value';
  $form['title']['#required'] = FALSE;
}

/**
 * Implements hook_node_presave()
 *  This func inserts the field_autocomplete value from the drug node type
 *  that was referenced into the
 *  node title before the node is saved.
 *  TThe title of the price report nodes are derived from, and what the
 *  autocomplete is built from (the titles of the price reports).
 */
function ssrx_pricereports_node_presave($node) {
  if ($node->type == 'drug_price') {
    $node->title = '';
    $ref = node_load($node->field_drug_variety[LANGUAGE_NONE][0]['nid']);
    $autocomplete = _ssrx_drug_get_autocomplete_value($ref);
    $node->title = $autocomplete;
  }
}